python metaworld_exp.py drawer-open-v2
python metaworld_exp.py drawer-close-v2
python metaworld_exp.py window-open-v2
python metaworld_exp.py window-close-v2
python metaworld_exp.py button-press-v2
python metaworld_exp.py sweep-into-v2
python metaworld_exp.py door-unlock-v2
python metaworld_exp.py door-close-v2
python metaworld_exp.py handle-pull-v2
python metaworld_exp.py handle-press-v2
python metaworld_exp.py handle-press-side-v2